# Generated by Django 4.0.5 on 2022-06-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=300)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('retired', models.BooleanField(default=True)),
                ('age', models.CharField(default=None, max_length=100)),
                ('teams', models.ManyToManyField(related_name='basketball', to='teams.team')),
            ],
        ),
    ]
